name: CommandSigns
main: com.hans.CommandSigns.CommandSigns
author: HansAnderson
version: 1.2.0
description: >
             Add commands to signs.
commands:
  commandsigns:
    aliases: [cmds]
    description: CommandSigns commands.
    usage: Type /<command> ? for help
permissions:
    CommandSigns.*:
        description: Gives access to all CommandSigns commands
        children:
            CommandSigns.create.regular: true
            CommandSigns.create.super: true
            CommandSigns.remove: true
            CommandSigns.use.regular: true
            CommandSigns.use.super: true
            CommandSigns.remove: true
            CommandSigns.debug: true
            CommandSigns.group.*: true
    CommandSigns.create.*:
        description: Gives access CommandSigns sign creation commands
        children:
            CommandSigns.create.regular: true
            CommandSigns.create.super: true
    CommandSigns.use.*:
        description: Gives access to CommandSigns sign use
        children:
            CommandSigns.use.regular: true
            CommandSigns.use.super: true
    CommandSigns.create.regular:
        description: Allows you to create a regular CommandSign
        default: op
    CommandSigns.create.super:
        description: Allows you to create a super CommandSign
        default: op
    CommandSigns.remove:
        description: Allows you to remove a CommandSign
        default: op
    CommandSigns.debug:
        description: Allows you to use debug
        default: op
    CommandSigns.use.regular:
        description: Allows you to use a regular CommandSign
        default: op
    CommandSigns.use.super:
        description: Allows you to use a super CommandSign
        default: op
    CommandSigns.group.*:
        description: Allows you to use all group commands
        default: op